// All visible text lives here so EN/ES stay in sync.

export const GITHUB_USER = "Afaguayo";
export const BIRTHDAY = { year: 2002, month: 11, day: 30 }; // Nov 30, 2002

// Repos to hide from the live GitHub list (the profile README repo, etc.).
export const HIDDEN_REPOS = ["Afaguayo"];

export const CONTACT = {
  location: "Chihuahua, Chihuahua, MX",
  phoneDisplay: "+52 614 154 2124",
  phoneHref: "tel:+526141542124",
  email: "angelaguayo78@outlook.com",
  github: "https://github.com/Afaguayo",
  resume: `${process.env.NEXT_PUBLIC_BASE_PATH || ""}/Angel%20Aguayo%20Resume.pdf`,
};

export const skills = [
  "Python", "TypeScript", "JavaScript", "Java", "C", "PHP", "Kotlin",
  "React", "Next.js", "Node.js", "Flask", "Tailwind CSS",
  "SQL", "MySQL", "MongoDB", "Firebase",
  "AWS", "Google Cloud", "Docker", "CI/CD", "Git",
  "Linux", "Bash", "PowerShell", "System Calls",
  "Machine Learning", "Deep Learning", "TensorFlow", "PyTorch", "scikit-learn", "Pandas", "NumPy",
  "Penetration Testing", "OAuth", "System Design", "Testing",
];

type Lang = "en" | "es";

export const t = {
  en: {
    boot: [
      "MAGI SYSTEM v3.02  (c) 2002-2026",
      "MELCHIOR-1 ............ ONLINE",
      "BALTHASAR-2 ........... ONLINE",
      "CASPER-3 .............. ONLINE",
      "SCANNING SECTOR 614 ... PATTERN BLUE",
      ">> ANGEL CONFIRMED. SYNC START.",
    ],
    skip: "press any key to skip",
    alert: "ANGEL DETECTED ◆ PATTERN BLUE ◆ SYNC RATIO 100% ◆ ALL SYSTEMS NOMINAL ◆",
    cards: {
      stats: { ep: "EPISODE:01", card: "PILOT DATA" },
      projects: { ep: "EPISODE:02", card: "UNITS DEPLOYED" },
      log: { ep: "EPISODE:03", card: "MEMORY" },
      contact: { ep: "EPISODE:04", card: "OPEN CHANNEL" },
      music: { ep: "EPISODE:05", card: "SOUND ONLY" },
      games: { ep: "EPISODE:06", card: "PLAYER TWO" },
    },
    nav: { home: "HOME", stats: "STATS", projects: "PROJECTS", log: "LOG", contact: "CONTACT", music: "MUSIC", games: "GAMES" },
    tagline: "software_engineer --cybersecurity --ai",
    role: "CS GRADUATE · SOFTWARE ENGINEER",
    start: "PRESS START",
    stats: {
      title: "PLAYER.STATS",
      level: "LV.",
      levelNote: (days: number) => (days === 0 ? "level up today!" : `next level-up in ${days} days`),
      class: "CLASS",
      classValue: "CS Graduate",
      base: "BASE",
      status: "STATUS",
      online: "ONLINE",
      langs: "LANGUAGES",
      langsValue: "English · Español",
      skills: "SKILLS.DAT",
    },
    music: {
      title: "NOW_SPINNING.TOP5",
      sub: "my most-played tracks this month, straight from Spotify",
      offline: "signal lost: spotify feed offline",
      play: "Play 30s preview",
      stop: "Stop preview",
      noPreview: "No preview available; open in Spotify",
      previewNote: "▶ plays a 30s preview",
      updated: "updated",
    },
    projects: {
      title: "PROJECTS.EXE",
      sub: "pulled live from github.com/Afaguayo",
      loading: "reading memory unit...",
      error: "github.net unreachable. browse the repos directly:",
      open: "OPEN REPO",
      demo: "LIVE DEMO",
      updated: "updated",
      all: "VIEW ALL ON GITHUB",
      noDesc: "no description yet",
    },
    log: {
      title: "JOURNEY.LOG",
      journey: [
        ["2020", "Started coding."],
        ["2021", "Got into UTEP and learned Java."],
        ["2022", "Learned Python, C, databases and operating systems."],
        ["2023", "Joined AI4ALL; learned ML and AI development."],
        ["2024", "Studied neural networks and modern AI."],
        ["2025", "Went deep into cybersecurity."],
        ["NOW", "CS graduate, shipping AI, security and desktop tools from Chihuahua."],
      ],
      expTitle: "EXPERIENCE.SYS",
      expRole: "AI4ALL, Instructor Assistant",
      exp: [
        "Designed and built a server-automation bot to streamline registrations.",
        "Managed and maintained the program's servers so operations ran smoothly.",
        "Helped organize the AI4ALL College Pathways program, supporting staff and participants.",
      ],
    },
    contact: {
      title: "CONTACT.CFG",
      sub: "open to work, collabs and good conversations",
      location: "location",
      phone: "phone",
      email: "email",
      github: "github",
      resume: "DOWNLOAD RESUME",
    },
    games: {
      title: "STEAM.TOP5",
      sub: { month: "my most-played Steam games this month", "2weeks": "my most-played Steam games, last 2 weeks" },
      offline: "signal lost: steam feed offline",
      hours: "h",
      updated: "updated",
    },
    offDuty: "OFF DUTY // the fun stuff",
    footer: "GOD'S IN HIS HEAVEN. ALL'S RIGHT WITH THE WORLD.",
  },
  es: {
    boot: [
      "SISTEMA MAGI v3.02  (c) 2002-2026",
      "MELCHIOR-1 ............ EN LÍNEA",
      "BALTHASAR-2 ........... EN LÍNEA",
      "CASPER-3 .............. EN LÍNEA",
      "ESCANEANDO SECTOR 614 . PATRÓN AZUL",
      ">> ÁNGEL CONFIRMADO. INICIANDO SINCRONÍA.",
    ],
    skip: "presiona cualquier tecla para saltar",
    alert: "ÁNGEL DETECTADO ◆ PATRÓN AZUL ◆ SINCRONÍA 100% ◆ SISTEMAS EN ORDEN ◆",
    cards: {
      stats: { ep: "EPISODIO:01", card: "DATOS DEL PILOTO" },
      projects: { ep: "EPISODIO:02", card: "UNIDADES DESPLEGADAS" },
      log: { ep: "EPISODIO:03", card: "MEMORIA" },
      contact: { ep: "EPISODIO:04", card: "CANAL ABIERTO" },
      music: { ep: "EPISODIO:05", card: "SOLO SONIDO" },
      games: { ep: "EPISODIO:06", card: "JUGADOR DOS" },
    },
    nav: { home: "INICIO", stats: "STATS", projects: "PROYECTOS", log: "LOG", contact: "CONTACTO", music: "MÚSICA", games: "JUEGOS" },
    tagline: "ingeniero_de_software --ciberseguridad --ia",
    role: "EGRESADO CS · INGENIERO DE SOFTWARE",
    start: "PRESIONA START",
    stats: {
      title: "JUGADOR.STATS",
      level: "NV.",
      levelNote: (days: number) => (days === 0 ? "¡sube de nivel hoy!" : `siguiente nivel en ${days} días`),
      class: "CLASE",
      classValue: "Egresado de Ciencias de la Computación",
      base: "BASE",
      status: "ESTADO",
      online: "EN LÍNEA",
      langs: "IDIOMAS",
      langsValue: "Español · English",
      skills: "HABILIDADES.DAT",
    },
    music: {
      title: "SONANDO.TOP5",
      sub: "mis canciones más escuchadas del mes, directo de Spotify",
      offline: "señal perdida: spotify sin conexión",
      play: "Reproducir 30s",
      stop: "Detener",
      noPreview: "Sin vista previa; abrir en Spotify",
      previewNote: "▶ reproduce 30s de la canción",
      updated: "actualizado",
    },
    projects: {
      title: "PROYECTOS.EXE",
      sub: "en vivo desde github.com/Afaguayo",
      loading: "leyendo memory unit...",
      error: "github.net no responde. mira los repos directamente:",
      open: "ABRIR REPO",
      demo: "DEMO",
      updated: "actualizado",
      all: "VER TODO EN GITHUB",
      noDesc: "sin descripción aún",
    },
    log: {
      title: "TRAYECTORIA.LOG",
      journey: [
        ["2020", "Empecé a programar."],
        ["2021", "Entré a UTEP y aprendí Java."],
        ["2022", "Aprendí Python, C, bases de datos y sistemas operativos."],
        ["2023", "Me uní a AI4ALL; aprendí desarrollo de ML e IA."],
        ["2024", "Estudié redes neuronales e IA moderna."],
        ["2025", "Me metí de lleno a la ciberseguridad."],
        ["HOY", "Egresado de CS, creando herramientas de IA, seguridad y escritorio desde Chihuahua."],
      ],
      expTitle: "EXPERIENCIA.SYS",
      expRole: "AI4ALL, Asistente de Instructor",
      exp: [
        "Diseñé y construí un bot de automatización de servidores para agilizar registros.",
        "Administré y mantuve los servidores del programa para que todo funcionara sin problemas.",
        "Ayudé a organizar el programa AI4ALL College Pathways, apoyando al equipo y a participantes.",
      ],
    },
    contact: {
      title: "CONTACTO.CFG",
      sub: "abierto a trabajo, colaboraciones y buenas pláticas",
      location: "ubicación",
      phone: "teléfono",
      email: "correo",
      github: "github",
      resume: "DESCARGAR CV",
    },
    games: {
      title: "STEAM.TOP5",
      sub: { month: "mis juegos de Steam más jugados este mes", "2weeks": "mis juegos de Steam más jugados, últimas 2 semanas" },
      offline: "señal perdida: steam sin conexión",
      hours: "h",
      updated: "actualizado",
    },
    offDuty: "FUERA DE SERVICIO // lo divertido",
    footer: "DIOS ESTÁ EN SU CIELO. TODO ESTÁ BIEN EN EL MUNDO.",
  },
} satisfies Record<Lang, unknown>;

export type Copy = (typeof t)["en"];
export type { Lang };
